# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sulkyjp.ZenithFiler
PackageVersion: 1.17.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ZenithFiler.exe
ArchiveBinariesDependOnPath: true
ReleaseDate: 2026-10-05
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/sulkyjp/zenithFiler_update/releases/download/v1.17.2/ZenithFiler_v1.17.2.zip
    InstallerSha256: 98562D497F7AF3A1CB4CD3E341B990BDCDB1F554BF73B5AF7D698102C4732C25
ManifestType: installer
ManifestVersion: 1.12.0
